a = float(input('Digite o valor A da sua equação do segundo grau: '))
b = float(input('Digite o valor B da sua equação do segundo grau: '))
c = float(input('Digite o valor C da sua equação do segundo grau: '))
print('')
deltaI = float(-4 * a * c)
deltaII = float(b ** 2)
delta = float(deltaII + deltaI)
print('Δ = -b² -4 x a x c')
print('Δ = -({})² -4 x {} x {}'.format(b, a, c))
print('Δ = {} + {}'.format(deltaII, deltaI))
print('')
print('O valor de delta e {}'.format(delta))
print('')
bmenos = float(-b)
raiz = float(delta ** (1/2))
denominador = float(2 * a)
print('X = (-b +- √Δ)÷ 2 x a')
print('X = ({} +- √{})÷ 2 x {}'.format(bmenos, delta, a))
print('X = ({} +- {:.2f})÷ 2 x {}'.format(bmenos, raiz, a))
print('X = ({} +- {:.2f})÷ {}'.format(bmenos, raiz, denominador))
print('')
print('se X for positivo:')
sobreI = float(bmenos + raiz)
XI = float(sobreI / denominador)
print('XI = ({} + {:.2f})÷ {}'.format(bmenos, raiz, denominador))
print('XI = {:.2f} ÷ {}'.format(sobreI, denominador))
print('XI = {:.2f}'.format(XI))
print('')
print('se for negativo:')
sobreII = float(bmenos - raiz)
XII = float(sobreII / denominador)
print('XII = ({} - {:.2f})÷ {}'.format(bmenos, raiz, denominador))
print('XII = {:.2f} ÷ {}'.format(sobreII, denominador))
print('XII = {:.2f}'.format(XII))
