a = float(input('Digite o valor A da sua equação do segundo grau: '))
b = float(input('Digite o valor B da sua equação do segundo grau: '))
c = float(input('Digite o valor C da sua equação do segundo grau: '))
delta = float((b * b)-4 * a * c)
print('O valor de delta e {}'.format(delta))
Xi = float(-b)
Xii = float(delta ** (1/2))
XI = float(Xi + Xii)
XIi = float(2 * a)
XId = float(XI / XIi)
print('(-b +- √Δ)÷ 2 x a')
print('({} +- √{})÷ 2 x {}'.format(Xi, delta, a))
print('({} +- {:.2f})÷ 2 x {}'.format(Xi, Xii, a))
print('({} +- {:.2f})÷ {}'.format(Xi, Xii, XIi))
print('')
print('se for positivo:')
print('{:.2f} ÷ {}'.format(XI, XIi))
print(XId.__round__(2))
print('')
XII = float(Xi - Xii)
XIId = (XII / XIi)
print('se for negativo:')
print('{:.2f} ÷ {}'.format(XII, XIi))
print(XIId.__round__(2))
